version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: notes-postgres
    environment:
      POSTGRES_DB: notedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A@077068
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host

  backend:
    image: abadaidjah/la-maligne-backend:latest
    container_name: notes-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/notedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: A@077068
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      APP_FRONTEND_URL: http://localhost:5173
      APP_BACKEND_URL: http://localhost:8081
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:5173
    ports:
      - "8081:8081"
    command: sh -c "sleep 10 && java -jar /app/target/demo-0.0.1-SNAPSHOT.jar"
    depends_on:
      - postgres
    network_mode: host  

  frontend:
    image: abadaidjah/la-maligne-frontend:latest
    container_name: notes-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    network_mode: host 
    environment:
      - VITE_API_URL=http://localhost:8081

volumes:
  postgres_data:

